In [1]:
def zeros(m,n):
    return [[0]*n for x in range(m)]

def constant(m,n,c):
    return [[c]*n for x in range(m)]

def ones(m,n,c):
    return constant(m,n,1)

def eye(n):
    x = zeros(n,n)
    for i in range(n):
        x[i][i]=1
    return x

def is_matrix(matrix):
    if type(matrix)!=list:
        print("Not a matrix")
        return False
    if type(matrix[0])!=list:
        print("Not a matrix")
        return False
    _ = len(matrix[0])
    for i in matrix:
        if len(i)!=_:
            print("Not a matrix")
            return False
    return True

def shape(matrix):
    if not is_matrix(matrix):
        return
    row_len = len(matrix)
    col_len = len(matrix[0])
    return (row_len,col_len)

def is_square_matrix(matrix):
    x,y = shape(matrix)
    if x != y:
        print("Not a square matrix")
        return False
    return True

def matrix_add(a,b):
    if not is_matrix(a): 
        print("A is not a matrix")
        return 
    if not is_matrix(b):
        print("B is not a matrix")
        return 
    if shape(a)!=shape(b):
        print("Matrices must be the same shape")
        return 
    row,col = shape(a)
    return_matrix = zeros(row,col)
    for i in range(len(a)):
        for j in range(len(a[i])):
            return_matrix[i][j] = a[i][j]+b[i][j]
    return return_matrix

def matrix_neg(matrix):  
    return matrix_scalar_multiply(-1,matrix)

def matrix_sub(a,b):
    return matrix_add(a,matrix_neg(b))

def transpose(matrix):
    if not is_matrix(matrix): 
        print("Error. Not a matrix")
        return 
    col,row = shape(matrix)
    return_matrix = zeros(row,col)
    for i in range(row):
        for j in range(col):
            return_matrix[i][j]=matrix[j][i]
    return return_matrix

def matrix_scalar_multiply(scalar,matrix):
    if not is_matrix(matrix): 
        print("Error. Not a matrix")
        return 
    row,col = shape(matrix)
    return_matrix = zeros(row,col)
    for i in range(row):
        for j in range(col):
            return_matrix[i][j]=matrix[i][j]*scalar
    return return_matrix

def matrix_multiply(M1,M2):
    m1,n1=shape(M1)
    m2,n2=shape(M2)
    
    if n1==m2:
        
        M3=zeros(m1,n2)
        
        for i in range(m1):
            for j in range(n2):
                # Compute the element
                for k in range(n1):
                    M3[i][j]+=M1[i][k]*M2[k][j]
        return M3
    else:
        print("Error, matrix dimensions do not match.")
    
def elementwise_multiply(M1,M2):
    m1,n1=shape(M1)
    m2,n2=shape(M2)
    
    if m1==m2 and n1==n2:
        M3 = zeros(m1,n1)
        for i in range(m1):
            for j in range(n1):
                M3[i][j] = M1[i][j]*M2[i][j]
        return M3
    else:
        print("Error: matrices must be the same shape.")
        
def dot_product(M1,M2):
    m1,n1=shape(M1)
    m2,n2=shape(M2)
    
    if m1==m2 and n1==n2:
        dotprod = 0
        for i in range(m1):
            for j in range(n1):
                dotprod += M1[i][j]*M2[i][j]
        return dotprod
    else:
        print("Error: matrices must be the same shape.")

In [16]:
class Matrix:
    
    def __init__(self, lst = None, n = None, m = None):
        if lst == None and type(n) == int and type(m) == int:
            self.matrix = [[0]*n for x in range(m)]
        elif (all(type(i) == list for i in lst) and all(len(i) == len(lst[0]) for i in lst)):
            self.matrix = [i for i in lst]
        else:
            print("There is an error in the Matrix!")
            
    def __getitem__(self, index):
        if isinstance(index, int):
            return self.matrix[index]
        elif len(index) == 2:
            i,j = index
            i = int(i)
            j = int(j)
            return self.matrix[i][j]
        
    def __str__(self):
        matrix_disp = "["+str(self.matrix[0]).replace(",","")+"\n"
        for i in range(1,len(self.matrix)-1):
            matrix_disp +=" "+str(self.matrix[i]).replace(",","")+"\n"
        matrix_disp +=" "+str(self.matrix[len(self.matrix)-1]).replace(",","")+"]"+"\n"
        return matrix_disp

    def __mul__(self, c):
        if not is_matrix(self.matrix): 
            print("Error. Not a matrix")
            return 
        row,col = shape(self.matrix)
        return_matrix = zeros(row,col)
        for i in range(row):
            for j in range(col):
                return_matrix[i][j]=self.matrix[i][j]*c
        return return_matrix
    
    def __mul__(self, M2):
        m1,n1=shape(self.matrix)
        m2,n2=shape(M2)
    
        if m1==m2 and n1==n2:
            M3 = zeros(m1,n1)
            for i in range(m1):
                for j in range(n1):
                    M3[i][j] = self.matrix[i][j]*M2[i][j]
            return M3
        else:
            print("Error: matrices must be the same shape.")
    
    def __rmul__(self, c):
        if not is_matrix(self.matrix): 
            print("Error. Not a matrix")
            return 
        row,col = shape(self.matrix)
        return_matrix = zeros(row,col)
        for i in range(row):
            for j in range(col):
                return_matrix[i][j]=self.matrix[i][j]*c
        return return_matrix

    def __add__(self ,b):
        if not is_matrix(self.matrix): 
            print("A is not a matrix")
            return 
        if not is_matrix(b):
            print("B is not a matrix")
            return 
        if shape(self.matrix)!=shape(b):
            print("Matrices must be the same shape")
            return 
        row,col = shape(self.matrix)
        return_matrix = zeros(row,col)
        for i in range(len(self.matrix)):
            for j in range(len(self.matrix[i])):
                return_matrix[i][j] = self.matrix[i][j]+b[i][j]
        return return_matrix
    
    def __sub__(self, b):
        return matrix_add(self.matrix ,matrix_neg(b))
    
    def dot_product(self, M2):
        m1,n1=shape(self.matrix)
        m2,n2=shape(M2)
    
        if m1==m2 and n1==n2:
            dotprod = 0
            for i in range(m1):
                for j in range(n1):
                    dotprod += self.matrix[i][j]*M2[i][j]
            return dotprod
        else:
            print("Error: matrices must be the same shape.")
    
    def matrix_neg(matrix):  
        return matrix_scalar_multiply(-1,matrix)

    def matrix_scalar_multiply(scalar,matrix):
        if not is_matrix(matrix): 
            print("Error. Not a matrix")
            return 
        row,col = shape(matrix)
        return_matrix = zeros(row,col)
        for i in range(row):
            for j in range(col):
                return_matrix[i][j]=matrix[i][j]*scalar
        return return_matrix

In [17]:
matrix = Matrix([[1,1,1], [1,1,1], [1,1,1]],None, None)
matrix2 = [[100, 100, 100],[100, 100, 100],[100, 100, 100]]
my = Matrix([[1,1,1], [1,1,1], [1,1,1]],None, None)

print(matrix.__str__())
M = matrix * 2
print(M.__str__())
N = 2 * matrix
print(N.__str__())
P = matrix + matrix2
print(P.__str__())
L = matrix - matrix2
print(L.__str__())

[[1 1 1]
 [1 1 1]
 [1 1 1]]

Not a matrix


TypeError: cannot unpack non-iterable NoneType object

In [15]:
print(type(matrix2))
K = matrix * matrix2
print(K.__str__())


<class 'list'>


TypeError: can't multiply sequence by non-int of type 'Matrix'