In [4]:
def zeros(m,n):
    return [[0]*n for x in range(m)]

def constant(m,n,c):
    return [[c]*n for x in range(m)]

def ones(m,n,c):
    return constant(m,n,1)

def eye(n):
    x = zeros(n,n)
    for i in range(n):
        x[i][i]=1
    return x

def is_matrix(matrix):
    if type(matrix)!=list:
        print("Not a matrix")
        return False
    if type(matrix[0])!=list:
        print("Not a matrix")
        return False
    _ = len(matrix[0])
    for i in matrix:
        if len(i)!=_:
            print("Not a matrix")
            return False
    return True

def shape(matrix):
    if not is_matrix(matrix):
        return
    row_len = len(matrix)
    col_len = len(matrix[0])
    return (row_len,col_len)

def is_square_matrix(matrix):
    x,y = shape(matrix)
    if x != y:
        print("Not a square matrix")
        return False
    return True

def matrix_add(a,b):
    if not is_matrix(a): 
        print("A is not a matrix")
        return 
    if not is_matrix(b):
        print("B is not a matrix")
        return 
    if shape(a)!=shape(b):
        print("Matrices must be the same shape")
        return 
    row,col = shape(a)
    return_matrix = zeros(row,col)
    for i in range(len(a)):
        for j in range(len(a[i])):
            return_matrix[i][j] = a[i][j]+b[i][j]
    return return_matrix

def matrix_neg(matrix):  
    return matrix_scalar_multiply(-1,matrix)

def matrix_sub(a,b):
    return matrix_add(a,matrix_neg(b))

def transpose(matrix):
    if not is_matrix(matrix): 
        print("Error. Not a matrix")
        return 
    col,row = shape(matrix)
    return_matrix = zeros(row,col)
    for i in range(row):
        for j in range(col):
            return_matrix[i][j]=matrix[j][i]
    return return_matrix

def matrix_scalar_multiply(scalar,matrix):
    if not is_matrix(matrix): 
        print("Error. Not a matrix")
        return 
    row,col = shape(matrix)
    return_matrix = zeros(row,col)
    for i in range(row):
        for j in range(col):
            return_matrix[i][j]=matrix[i][j]*scalar
    return return_matrix

def matrix_multiply(M1,M2):
    m1,n1=shape(M1)
    m2,n2=shape(M2)
    
    if n1==m2:
        
        M3=zeros(m1,n2)
        
        for i in range(m1):
            for j in range(n2):
                # Compute the element
                for k in range(n1):
                    M3[i][j]+=M1[i][k]*M2[k][j]
        return M3
    else:
        print("Error, matrix dimensions do not match.")
    
def elementwise_multiply(M1,M2):
    m1,n1=shape(M1)
    m2,n2=shape(M2)
    
    if m1==m2 and n1==n2:
        M3 = zeros(m1,n1)
        for i in range(m1):
            for j in range(n1):
                M3[i][j] = M1[i][j]*M2[i][j]
        return M3
    else:
        print("Error: matrices must be the same shape.")
        
def dot_product(M1,M2):
    m1,n1=shape(M1)
    m2,n2=shape(M2)
    
    if m1==m2 and n1==n2:
        dotprod = 0
        for i in range(m1):
            for j in range(n1):
                dotprod += M1[i][j]*M2[i][j]
        return dotprod
    else:
        print("Error: matrices must be the same shape.")

# Matrix Class
The following code gives a basic matrix class with the following properties:
1. Matrices are be represented as lists of lists as we have done before
1. The class can be initialized in 2 ways:
    1. with arguments `n` and `m`, the size of the matrix. A newly instanciated matrix will contain all zeros.
    1. with a list of lists of values. Note that since we are using lists of lists to implement matrices, it is possible that a user provides a list so that not all rows have the same number of columns. Test explicitly that the matrix is properly specified.
1. Matrix instances M can be indexed with `M[i][j]` and `M[i,j]`.

In [5]:
class Matrix:
    
    def __init__(self, lst = None, n = None, m = None):
        if lst == None and type(n) == int and type(m) == int:
            self.matrix = [[0]*n for x in range(m)]
        elif (all(type(i) == list for i in lst) and all(len(i) == len(lst[0]) for i in lst)):
            self.matrix = [i for i in lst]
        else:
            print("There is an error in the Matrix!")
            
    def __getitem__(self, index):
        if isinstance(index, int):
            return self.matrix[index]
        elif len(index) == 2:
            i,j = index
            i = int(i)
            j = int(j)
            return self.matrix[i][j]
        
    def __str__(self):
        matrix_disp = "["+str(self.matrix[0]).replace(",","")+"\n"
        for i in range(1,len(self.matrix)-1):
            matrix_disp +=" "+str(self.matrix[i]).replace(",","")+"\n"
        matrix_disp +=" "+str(self.matrix[len(self.matrix)-1]).replace(",","")+"]"+"\n"
        return matrix_disp

    def scalarmul(self, c):
        if not is_matrix(self.matrix): 
            print("Error. Not a matrix")
            return 
        row,col = shape(self.matrix)
        return_matrix = zeros(row,col)
        for i in range(row):
            for j in range(col):
                return_matrix[i][j]=self.matrix[i][j]*c
        return return_matrix
    
    def matrix_add(self ,b):
        if not is_matrix(self.matrix): 
            print("A is not a matrix")
            return 
        if not is_matrix(b):
            print("B is not a matrix")
            return 
        if shape(self.matrix)!=shape(b):
            print("Matrices must be the same shape")
            return 
        row,col = shape(self.matrix)
        return_matrix = zeros(row,col)
        for i in range(len(self.matrix)):
            for j in range(len(self.matrix[i])):
                return_matrix[i][j] = self.matrix[i][j]+b[i][j]
        return return_matrix
    
    def matrix_sub(self, b):
        return matrix_add(self.matrix ,matrix_neg(b))
    
    def dot_product(self, M2):
        m1,n1=shape(self.matrix)
        m2,n2=shape(M2)
    
        if m1==m2 and n1==n2:
            dotprod = 0
            for i in range(m1):
                for j in range(n1):
                    dotprod += self.matrix[i][j]*M2[i][j]
            return dotprod
        else:
            print("Error: matrices must be the same shape.")
    
    def elementwise_multiply(self, M2):
        m1,n1=shape(self.matrix)
        m2,n2=shape(M2)
    
        if m1==m2 and n1==n2:
            M3 = zeros(m1,n1)
            for i in range(m1):
                for j in range(n1):
                    M3[i][j] = self.matrix[i][j]*M2[i][j]
            return M3
        else:
            print("Error: matrices must be the same shape.")

Test the matrix class as follows:
1. Instantiate a new 2x2 matrix of zeros by passing arguments `n` and `m` to the Matrix class
1. Instantiate a new 3x3 matrix of ones by passing a list of lists to the Matrix class
1. Try to instantiate a matrix with a list of lists, but make the sub-lists different sizes (this will verify that the error state works in the object constructor).
1. Instantiate a 3x3 matrix with entries 1-9 and use print out the (1,1) index entry in both of the ways described in item 3 in the first cell above.
1. Print this full matrix using the `print` command (this verifies that the `__str__` method works).

In [6]:
twoxtwo = Matrix(None,2,2)
print(twoxtwo.__str__())

threexthree = Matrix([[1,1,1], [1,1,1], [1,1,1]],None, None)
print(threexthree.__str__())

errorState = Matrix([[1,1], [0,3,4]], None, None)

my_matrix = Matrix([[1,3,4], [3,3,7], [2,3,8]], None, None)
print(my_matrix.__str__())
my_matrix.__getitem__('11')

[[0 0]
 [0 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

There is an error in the Matrix!
[[1 3 4]
 [3 3 7]
 [2 3 8]]



3

## Exercise 2 &ndash; Internal methods
Add the following methods to your class (note you may call the functions below in these methods). Make sure to appropriately test the dimensions of the matrices to make sure the operations are correct.
1. `M.scalarmul(c)`: a matrix that is the scalar product $cM$, where every element of $M$ is multiplied by $c$.
1. `M.add(N)`: adds two matrices $M$ and $N$. Don’t forget to test that the sizes of the matrices are compatible for this and all other operations.
1. `M.sub(N)`: subtracts two matrices: $M-N$.
1. `M.mat_mult(N)`: returns a matrix that is the matrix product of two matrices $MN$.
1. `M.element_mult(N)`: returns a matrix that is the element-wise product of two matrices $M$ and $N$.
1. `M.equals(N)`: returns true/false if $M==N$.

In [7]:
threexthree = Matrix([[1,1,1], [1,1,1], [1,1,1]],None, None)
matrix = [[100, 100, 100],[100, 100, 100],[100, 100, 100]]
print(threexthree.scalarmul(4))
print(threexthree.matrix_add(matrix))
print(threexthree.matrix_sub(matrix))
print(threexthree.dot_product(matrix))
print(threexthree.elementwise_multiply(matrix))


[[4, 4, 4], [4, 4, 4], [4, 4, 4]]
[[101, 101, 101], [101, 101, 101], [101, 101, 101]]
[[-99, -99, -99], [-99, -99, -99], [-99, -99, -99]]
900
[[100, 100, 100], [100, 100, 100], [100, 100, 100]]


## Exercise 3
Modify the functions `zeros`, `ones`, and `constant` (of your own or those below) to create objects of your matrix class. Note these should be functions **outside** of your class.

In [18]:
def zeros(m,n):
    zeros = Matrix(None, m, n)
    return zeros

def constant(m,n,c):
    constant = Matrix(None, m, n)
    constant = (constant.scalarmul(c))
    return constant

def ones(m,n,c):
    return constant(m,n,1)

print(zeros(3,3))
print(constant(3,3,100))
print(ones(2,2,99))

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0]
 [0 0]]



## Exercise 4
Overload python operators to appropriately use your functions in 4 and allow expressions like:
- 2*M
- M*2
- M+N
- M-N
- M*N
- M==N
- M=N

1. Matrix assignment ($M=N$) works in 2 ways and can be implemented as a method titled `__eq__`:
        1. If `M_1` and `M_2` are `matrix` instances `M_1=M_2` sets the values of `M_1` to those of `M_2`, if they are the same size. Error otherwise.
        1. Assignment should also work if `M_2` is a list of lists of the correct size rather than an object of the matrix class.

You may find this tutorial useful https://realpython.com/operator-function-overloading.

Demonstrate the basic properties of matrices with your matrix class by creating 2 by 2 example matrices using your Matrix class and illustrating the following:
($A$, $B$, and $C$ are matrices, and $I$ is the identity matrix $\begin{bmatrix} 1 & 0\\ 0 & 1\end{bmatrix}$)

1. $(AB)C = A(BC)$
1. $A(B+C)=AB+AC$
1. $AB \neq BA$
1. $AI = A$
1. $AB = 0$ if $B$ is the 0 matrix

In [24]:
matrix = Matrix(None,2,2)
print(matrix.__str__())

[[0 0]
 [0 0]]

