## Exercise 1
1. Generate an ndarray with 2 rows, each containing 10 random integers between 1 and 10 (*Hint:* Lookup syntax of `numpy.random.randint`)
1. Assuming your array is called `a`, print all of the following commands: `a.shape`, `numpy.sum(a)`, `numpy.sum(a,axis=0)`, and `numpy.sum(a,axis=1)`.  Explain what each is doing.

In [30]:
import numpy as np
import matplotlib.pyplot as plt
x = (np.random.randint(0,10, size = 10))
c = (np.random.randint(0,10, size = 10))
A = np.vstack([x, c])
print(A)
print(type(A))
print("A.Shape is (It prints out the dimensions of the arrays which is 2 rows and 10 columns) - ",
         A.shape,"\nnp.sum(A) is (It sums the elements of array) - ", np.sum(A),"\nnp.sum(A, axis=0)  (It sums the elements of array and axis 0 means along the columns) - ",
          np.sum(A,axis=0),"\nnp.sum(A,axis=1) (It sums the elements of array and axis 1 means along the rows) - ", np.sum(A,axis=1))

[[6 2 9 4 8 6 5 5 1 3]
 [4 9 5 7 8 4 2 5 4 3]]
<class 'numpy.ndarray'>
A.Shape is (It prints out the dimensions of the arrays which is 2 rows and 10 columns) -  (2, 10) 
np.sum(A) is (It sums the elements of array) -  100 
np.sum(A, axis=0)  (It sums the elements of array and axis 0 means along the columns) -  [10 11 14 11 16 10  7 10  5  6] 
np.sum(A,axis=1) (It sums the elements of array and axis 1 means along the rows) -  [49 51]


## Exercise 2
1. For a given variable `num_trials`, generate a `100` by `num_trials` ndarray with entries from the standard normal distribution (look up the syntax for `numpy.random.randn`).
1. For each of the following values of `num_trials` $\{10,100,1000,10000,1000000\}$, generate the ndarray above.
1. For each value of `num_trials`, sum the columns of the ndarray (you should get a new ndarray of length `num_trials`).
1. Use pyplot to plot a histogram of the summed array for each value of `num_trials` and various numbers of bins.
1. Discuss any trends you see.

In [43]:
import numpy as np
import matplotlib.pyplot as plt
num_trials = np.random.randn(10)
num_trials1 = np.random.randn(100)
num_trials2 = np.random.randn(1000)
num_trials3 = np.random.randn(10000)
num_trials4 = np.random.randn(1000000)
x =  np.sum(num_trials, axis=0)
x1 = np.sum(num_trials1, axis=0)
x2 = np.sum(num_trials2, axis=0)
x3 = np.sum(num_trials3, axis=0)
x4 = np.sum(num_trials4, axis=0)
num_trials

array([-0.21424015, -1.09225917,  0.90415398, -0.30623427,  2.31906579,
        1.03819173,  1.24417003,  1.37214762, -0.21523766,  0.98693401])

## Exercise 3
1. Look up the syntax for the function `numpy.random.choice`
1. Create an array or list of the integers 1-10. 
1. Choose 15 integers from your list with the optional input argument to `numpy.random.choice` set to `replace=True`
1. Choose 15 integers from your list with the optional input argument to `numpy.random.choice` set to `replace=False`
1. What do you notice? Explain why?
1. Create a new array or list of integers 1-4, and create a set of probabilities as follows `probs = [.8, .1, .1, 0]`
1. Using the optional input argument `p=probs`, draw 20 numbers from your list 1-4 (with `replace=True`)
1. Count the percent of times each integer is drawn.
1. Repeat the last two items for drawing 100 numbers and then 1000 numbers from 1-4 with those probabilities
1. What do you notice? Explain why.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
lst = [1,2,3,4,5,6,7,8,9,10]
a = np.random.choice(lst, size=15, replace=True)
#b = np.random.choice(lst, size=15, replace=False)
# True means a value can be chosen twice, False gives error as it runs out of unique values to give
lst1 = [1,2,3,4]
probs = [0.8, 0.1, 0.1, 0.0]
a = np.random.choice(lst1, size=10, replace=True, p=probs)
b = np.random.choice(lst1, size=10, replace=True, p=probs)
print(a)
print(b)

[1 1 1 1 1 1 1 1 3 1]
[1 1 1 1 2 1 1 1 1 1]


## Exercise 4
1. Write a function that rolls a dice `n` times for a given integer `n` and computes a *running percentage* of times each number is rolled (# of times 1 has been rolled)/(# of rolls so far) and so on. That is, at the `i`-th roll, you should compute (# of 1s)/i, (# of 2s)/i, ... and store these values.
1. Modify this function to take in a probability distribution over the 6 numbers of the form `p=np.array([p1,p2,p3,p4,p5,p6])` and roll a dice `n` times with these probabilities
1. Run your function from part 1 with $n=1000$ and graph the rolling averages for all numbers vs. `i in range(n)`
1. Run your function from part 2 with $n=1000$ and $p= [.2,.1,.2,.1..1,.3]$
1. Use the plots above to justify that the first dice is fair and the second is unfair

In [41]:
import numpy as np
import matplotlib.pyplot as plt
n = 100
i = 5 #i - the roll i wanna stop at
ones = 0
twos = 0
threes = 0
fours = 0
fives = 0
sixes = 0
p = np.array([0.2,0.1,0.2,0.1,0.1,0.3])
for k in range(n):
    #print("Role number ", k+1)
    a = np.random.choice([1,2,3,4,5,6], replace=True, p=p)
    if (a == 1):
        ones = ones + 1
    elif (a == 2):
        twos = twos + 1
    elif (a == 3):
        threes = threes + 1
    elif (a == 4):
        fours = fours + 1
    elif (a == 5):
        fives = fives + 1
    elif (a == 6):
        sixes = sixes + 1
    #print("ones = ", ones, "\ntwos = ", twos, "\nthrees = ", threes, "\nfours = ", fours, "\nfives = ", fives, "\nsixes = ", sixes)
print("\n\nFINALLY\nones = ", ones, "\ntwos = ", twos, "\nthrees = ", threes, "\nfours = ", fours, "\nfives = ", fives, "\nsixes = ", sixes)
print("\nFINALLY\nones = ", (ones/n) * 100, "\ntwos = ", (twos/n) * 100, "\nthrees = ", (threes/n) * 100, "\nfours = ", (fours/n) * 100, "\nfives = ", (fives/n) * 100, "\nsixes = ", (sixes/n) * 100)



FINALLY
ones =  17 
twos =  10 
threes =  18 
fours =  11 
fives =  11 
sixes =  33

FINALLY
ones =  17.0 
twos =  10.0 
threes =  18.0 
fours =  11.0 
fives =  11.0 
sixes =  33.0
